CREATE TABLE IF NOT EXISTS public.companies
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(200) COLLATE pg_catalog."default",
    company_name character varying(200) COLLATE pg_catalog."default",
    fio character varying(200) COLLATE pg_catalog."default",
    inn character varying(200) COLLATE pg_catalog."default",
    kpp character varying(200) COLLATE pg_catalog."default",
    name character varying(200) COLLATE pg_catalog."default",
    ogrn character varying(200) COLLATE pg_catalog."default",
    post character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT companies_pkey PRIMARY KEY (id)
    )
